language: node_js
node_js:
  - "8"
  - "7"
  - "6"
  - "5"
  - "4"
  - "0.12"
  - "0.10"
  - "0.9"
  - "0.8"
matrix:
  include:
    - node_js: "6"
      env: TZ="America/New_York"
    - node_js: "8"
      env: TZ="America/Los_Angeles"
    - node_js: "6"
      env: TZ="Europe/London"
    - node_js: "8"
      env: TZ="Europe/Berlin"
    - node_js: "6"
      env: TZ="Asia/Kolkata"
    - node_js: "7"
      env: TZ="Asia/Shanghai"
    - node_js: "8"
      env: TZ="Asia/Seoul"
before_install:
  - "npm install -g npm@4.3.0"
  - "npm install -g mocha@2.x voc"
  - "npm install blanket"
  - "npm install coveralls mocha-lcov-reporter"
after_success:
  - "make coveralls"
